"""Initial schema (use `alembic revision --autogenerate` to generate real migrations).

After first run, replace this with the autogenerated diff against current models.
For day-1 onboarding the application also calls Base.metadata.create_all() on startup.
"""
from alembic import op  # noqa: F401
import sqlalchemy as sa  # noqa: F401

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Schema is created by SQLAlchemy on first boot (see app.main.lifespan).
    # Run `alembic revision --autogenerate -m "..."` to capture future migrations.
    pass


def downgrade() -> None:
    pass
