#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/../../.." && pwd)"
ENV_FILE="${ROOT_DIR}/.env.prod"
OUT_FILE="${ROOT_DIR}/deploy/internal/nginx/conf.d/allowlist.conf"

if [[ ! -f "${ENV_FILE}" ]]; then
  echo "Missing ${ENV_FILE}"
  exit 1
fi

set -a
source "${ENV_FILE}"
set +a

ALLOWED_CIDRS="${ALLOWED_CIDRS:-0.0.0.0/0}"

echo "# Generated by scripts/generate-allowlist.sh" > "${OUT_FILE}"
echo "# CIDR ingress rules for edge nginx." >> "${OUT_FILE}"

IFS=',' read -ra CIDRS <<< "${ALLOWED_CIDRS}"
for cidr in "${CIDRS[@]}"; do
  trimmed="$(echo "${cidr}" | xargs)"
  [[ -n "${trimmed}" ]] && echo "allow ${trimmed};" >> "${OUT_FILE}"
done

echo "deny all;" >> "${OUT_FILE}"

echo "Updated ${OUT_FILE}"
